#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: kubernetes-cluster-robertoledesma
---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: app-settings
#  namespace: kubernetes-cluster-robertoledesma
#data:
#  ENVIRONMENT: dev
#  MESSAGE: hola
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: secret-info
#  namespace: kubernetes-cluster-robertoledesma
#data:
#  USERNAME: YWRtaW4tZGV2
#  PASSWORD: cGFzc3dvcmQ=
#type: Opaque
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i-robertoledesma-develop-deployment
#  namespace: kubernetes-cluster-robertoledesma
spec:
  selector:
   matchLabels:
    app: i-robertoledesma-develop
  replicas: 4
  template:
    metadata:
      labels:
        app: i-robertoledesma-develop
    spec:
      containers:
        - name: i-robertoledesma-develop
          image: roblednag/i-robertoledesma-develop:latest
          ports:
            - containerPort: 8800
              name: devport
          #envFrom:
          #  - configMapRef:
          #      name: app-settings
          #  - secretRef:
          #      name: secret-info
---
apiVersion: v1
kind: Service
metadata:
  name: i-robertoledesma-develop-service
#  namespace: kubernetes-cluster-robertoledesma
  labels:
    app: i-robertoledesma-develop
spec:   
  ports:
  - name: i-robertoledesma-develop
    port: 8800
    nodePort : 30900
  type: LoadBalancer
  #type: NodePort
  selector:
   app: i-robertoledesma-develop

